/** This file is part of the HYB simulation platform.
 *
 *  Copyright 2014- Finnish Meteorological Institute
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef CONSTANTS_H

namespace cnst
{
 const double mp = 1.672621716e-27;
 const double me = 9.1093825746e-31;
 const double epsilon0 = 8.8541878176e-12;
 const double mu0 = 1.2566370614e-06;
 const double c = 2.99792458e8;
 const double kB = 1.3806505e-23;
 const double qe = 1.60217653e-19;
}

#define CONSTANTS_H
#endif
