#!/bin/csh
# hccomb: combine all *.hc.head, *.hc.nnnn, *.hc.tail.nnnn files --> *.hc files
# in current directory
#
# must use csh for {} patterns to work

# This file is part of the HYB simulation platform.
#
# Copyright 2014- Finnish Meteorological Institute
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

foreach i (*.hc.head)
	set f = `basename $i .head`
	if (! -f $i) then
		echo 'hccomb: No *.hc.head files in current directory'
		exit
	endif
	cat $i ${f}.{0,1,2,3,4,5,6,7,8,9}??? ${f}.tail.???? >>$f
	rm $i ${f}.{0,1,2,3,4,5,6,7,8,9}??? ${f}.tail.????
end

